name: Build and Deploy to EC2

on:
  push:
    branches:
      - master # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SOURCE: "build/"
          script: |
            cd ${{ secrets.TARGET_DIR }}
            npm install
            npm build
            npm i serve
            serve -p 3000 build/
